### ISSUE TITLE
update documentation for all pages

### ISSUE THREAD

**Issue by Ryan-Bauroth** [DurhamAcademy/ChocoChipScouting#190]
Not only does this mean documentation in code (which is required and should be to an extent that someone with almost no awareness of what is going on can figure things out) but also a document which describes how to set up and update this software for each new season. 

- [ ] Update readme
- [ ] Document pages
     - [x] matches.vue
     - [ ] teams/id.vue
     - [ ] teams/index.vue
     - [ ] teams/attachments/index.vue
     - [ ] teams/attachments/[id].vue
     - [ ] attachment/add.vue
     - [ ] attachments/[id].vue
     - [ ] dashboard.vue
     - [ ] login.vue
     - [ ] notes.vue
     - [ ] predict.vue
     - [x] settings.vue
     - [x] users.vue
     - [ ] index.vue
- [ ] separate components into previous season components and abstract components
- [ ] document components
- [ ] document util functions

**Comment by tslom** [comment]
ah hell
this is going to be a pain

**Comment by tslom** [comment]
can we like find an api that has all the scoring n stuff so that we can access it or something
